import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import supabase from "../lib/supabase";
import { generateNotes } from "../lib/gemini";

function TopicNotes({
  subject,
  topic,
}) {
  const [notes, setNotes] =
    useState("");

  const [loading, setLoading] =
    useState(true);
  const [generated, setGenerated] =
    useState(false);
  const [aiError, setAiError] =
    useState(null);

  useEffect(() => {
    setAiError(null);
    fetchNotes();
  }, [subject, topic]);

  const fetchNotes = async () => {
    setLoading(true);

    const { data, error } =
      await supabase
        .from("topic_notes")
        .select("*")
        .eq(
          "subject_name",
          subject
        )
        .eq(
          "topic_name",
          topic
        )
        .maybeSingle();

    if (error) {
      console.log(error);
      setLoading(false);
      return;
    }

    if (data?.notes?.trim()) {
      setNotes(data.notes);
      setGenerated(false);
      setLoading(false);
      return;
    }

    await generateAndStoreNotes(data?.id);
  };

  const generateAndStoreNotes =
    async (noteId) => {
      setLoading(true);

      try {
        const generatedNotes =
          await generateNotes(
            subject,
            topic
          );

        setNotes(generatedNotes);
        setGenerated(true);

        if (noteId) {
          await supabase
            .from("topic_notes")
            .update({ notes: generatedNotes })
            .eq("id", noteId);
        } else {
          await supabase.from("topic_notes").insert([
            {
              subject_name: subject,
              topic_name: topic,
              notes: generatedNotes,
            },
          ]);
        }
      } catch (error) {
        console.log(error);
        setAiError(error.message || "Failed to generate notes.");
      } finally {
        setLoading(false);
      }
    };

  const regenerateNotes = async () => {
    setGenerated(true);
    await generateAndStoreNotes();
  };

  if (loading) {
    return (
      <div className="mt-4">
        Loading Notes...
      </div>
    );
  }

  if (aiError) {
    return (
      <div className="bg-red-50 border border-red-200 p-4 rounded-lg mt-4">
        <h3 className="font-semibold text-red-700 mb-2">
          Unable to generate notes
        </h3>
        <p className="text-sm text-red-600 mb-3">
          {aiError}
        </p>
        <button
          onClick={generateAndStoreNotes}
          className="bg-red-600 text-white px-4 py-2 rounded-lg"
        >
          Retry
        </button>
      </div>
    );
  }

  const downloadPdf = () => {
    const doc = new jsPDF();
    const title = `${subject} - ${topic} Notes`;
    const content = `Subject: ${subject}\nTopic: ${topic}\n\n${notes}`;
    const lines = doc.splitTextToSize(content, 180);

    doc.setFontSize(14);
    doc.text(title, 10, 20);
    doc.setFontSize(11);
    doc.text(lines, 10, 30);
    doc.save(`${subject}-${topic}-notes.pdf`);
  };

  return (
    <div className="bg-yellow-50 border p-4 rounded-lg mt-4">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-3">
        <h3 className="font-bold text-xl">
          📖 Study Notes
        </h3>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={regenerateNotes}
            className="bg-violet-600 text-white px-4 py-2 rounded-lg"
          >
            Regenerate Notes
          </button>
          <button
            onClick={downloadPdf}
            className="bg-primary-600 text-white px-4 py-2 rounded-lg"
          >
            Download PDF
          </button>
        </div>
      </div>

      {generated && (
        <p className="text-sm text-slate-500 mb-3">
          Generated by AI because no saved notes were found.
        </p>
      )}

      <pre className="whitespace-pre-wrap">
        {notes}
      </pre>
    </div>
  );
}

export default TopicNotes;